export const SAVE_TO_LOCAL_STORAGE = 'SAVE_TO_LOCAL_STORAGE';
export const PROGRESS_PAGE_IF_NEEDED = 'PROGRESS_PAGE_IF_NEEDED';
export const CLEAR_LOCAL_STORAGE = 'CLEAR_LOCAL_STORAGE';

export const FETCH_SF_OBJECT_FIELDS = 'FETCH_SF_OBJECT_FIELDS';
export const FETCH_KNACK_OBJECT_FIELDS = 'FETCH_KNACK_OBJECT_FIELDS';

export const CHECK_REQUIRED_KNACK_FIELDS_MAPPED = 'CHECK_REQUIRED_KNACK_FIELDS_MAPPED';
