export const SF_SELECTED_OBJECT_PRETTY_NAME = 'SF_SELECTED_OBJECT_PRETTY_NAME';
export const SF_SELECTED_OBJECT_PRETTY_NAME_PLURAL = 'SF_SELECTED_OBJECT_PRETTY_NAME_PLURAL';
export const KNACK_SELECTED_OBJECT_PRETTY_NAME = 'KNACK_SELECTED_OBJECT_PRETTY_NAME';
