// src/js/lib/mutation-types.js

export const FINISHED_MOUNTING = 'FINISHED_MOUNTING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PAGE_ACTIVE = 'SET_PAGE_ACTIVE';
export const SET_PAGE_INACTIVE = 'SET_PAGE_INACTIVE';
export const RESET_KNACK_AUTH = 'RESET_KNACK_AUTH';
export const UPDATE_ACTIVE_PAGES = 'UPDATE_ACTIVE_PAGES';
export const RESTORE_FROM_LOCAL_STORAGE = 'RESTORE_FROM_LOCAL_STORAGE';

export const STORE_VALID_SF_CREDENTIALS = 'STORE_VALID_SF_CREDENTIALS';
export const SET_SF_ERR = 'SET_SF_ERR';
export const SET_SF_OBJECTS = 'SET_SF_OBJECTS';
export const SET_SF_SELECTED_OBJECT = 'SET_SF_SELECTED_OBJECT';
export const SET_SF_OBJECT_FIELDS = 'SET_SF_OBJECT_FIELDS';
export const SET_SF_AUTHORIZED = 'SET_SF_AUTHORIZED';

export const STORE_VALID_KNACK_CREDENTIALS = 'STORE_VALID_KNACK_CREDENTIALS';
export const SET_KNACK_AUTHORIZED = 'SET_KNACK_AUTHORIZED';
export const SET_KNACK_ERR = 'SET_KNACK_ERR';
export const SET_KNACK_OBJECTS = 'SET_KNACK_OBJECTS';
export const SET_KNACK_BASE_URL = 'SET_KNACK_BASE_URL';
export const SET_KNACK_SELECTED_OBJECT = 'SET_KNACK_SELECTED_OBJECT';
export const SET_KNACK_OBJECT_FIELDS = 'SET_KNACK_OBJECT_FIELDS';

/* OBJECT MAPPINGS */
export const ADD_OBJECT_FIELD_MAPPING = 'ADD_OBJECT_FIELD_MAPPING';
export const REMOVE_OBJECT_FIELD_MAPPING = 'REMOVE_OBJECT_FIELD_MAPPING';
export const SET_OBJECT_MAPPINGS_ERROR = 'SET_OBJECT_MAPPINGS_ERROR';
export const SET_OBJECT_MAPPINGS_REQUIRED_FIELDS_MISSING = 'SET_OBJECT_MAPPINGS_REQUIRED_FIELDS_MISSING';
export const RESET_SF_FIELD_MAPPINGS = 'RESET_SF_FIELD_MAPPINGS';
export const RESET_KNACK_FIELD_MAPPINGS = 'RESET_KNACK_FIELD_MAPPINGS';

/* IMPORT / EXPORT */
export const SET_IMPORT_EXPORT_STARTED = 'SET_IMPORT_EXPORT_STARTED';

export const SET_IMPORT_FINISHED = 'SET_IMPORT_FINISHED';
export const PUSH_IMPORT_ERR = 'PUSH_IMPORT_ERR';
export const PUSH_IMPORT_IMPORTED = 'PUSH_IMPORT_IMPORTED';
export const RESET_IMPORT = 'RESET_IMPORT';

export const SET_EXPORT_FINISHED = 'SET_EXPORT_FINISHED';
export const SET_EXPORT_ERR = 'SET_EXPORT_ERR';
export const SET_EXPORT_SF_OBJECTS = 'SET_EXPORT_SF_OBJECTS';
export const RESET_EXPORT = 'RESET_EXPORT';
