// src/js/lib/stateTypes.js

export const CURRENT_PAGE = 'CURRENT_PAGE';
export const MOUNTED = 'MOUNTED';
export const PAGES = 'PAGES';
export const KNACK = 'KNACK';
export const SF = 'SF';
export const OBJECT_MAPPINGS = 'OBJECT_MAPPINGS';
export const OBJECT_MAPPINGS_ERROR = 'OBJECT_MAPPINGS_ERROR';
export const OBJECT_MAPPINGS_REQUIRED_FIELDS_MISSING = 'OBJECT_MAPPINGS_REQUIRED_FIELDS_MISSING';

export const IMPORT_EXPORT_STARTED = 'IMPORT_EXPORT_STARTED';
export const IMPORT_INFO = 'IMPORT_INFO';
export const EXPORT_INFO = 'EXPORT_INFO';
